name = "hono-newsletter"
main = "src/index.ts"
compatibility_date = "2024-11-01"

compatibility_flags = [ "nodejs_compat" ]

[vars]
APP_BASE_URL = "https://hono-newsletter.milos-dzepina.workers.dev"
# DATABASE_URL = "secret"
EMAIL_BASE_URL = "https://api.mailjet.com/v3.1"
EMAIL_SENDER = "vjjv6ujvs@mozmail.com"
# EMAIL_API_KEY = "secret"
# EMAIL_API_SECRET = "secret"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1
